
-- grade 생성
select * from tb_grade2;

insert into tb_grade2 values(0, '관리자');
insert into tb_grade2 values(1, '결제 유저');
insert into tb_grade2 values(2, '비결제 유저');
insert into tb_grade2 values(3, '영구정지 유저');
select * from tb_grade2;

-- 게시글 분류
insert into tb_boardclass2 values(1, '공지사항');
insert into tb_boardclass2 values(2, '메이트찾기게시판');
insert into tb_boardclass2 values(3, '모집 게시판');
insert into tb_boardclass2 values(4, '후기 게시판');
insert into tb_boardclass2 values(5, '문의 게시판');
insert into tb_boardclass2 values(6, '이벤트 등록 게시판');

select * from tb_boardclass2;

--신고사유테이블
insert into tb_reportreason2 (reason_content) values ('욕설 신고');
insert into tb_reportreason2 (reason_content) values ('스팸 및 광고 신고');
insert into tb_reportreason2 (reason_content) values ('비매너(노쇼 등) 신고');
insert into tb_reportreason2 (reason_content) values ('먹튀 신고');
insert into tb_reportreason2 (reason_content) values ('기타 사유 신고');

select * from tb_reportreason2;

--신고처리내용테이블
insert into tb_resultreportreason2 (report_result_content) values( '영구 정지');
select * from tb_resultreportreason2;

-- 회원 정보 더미데이터
drop table tb_user2;
select * from tb_user2
order by user_no;

insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf1', 'asdf1', 'asdf1', 'M', '20', 0, 'asdf1@a.com',0);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf2', 'asdf2', 'asdf2', 'F', '21', 1, 'asdf2@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf3', 'asdf3', 'asdf3', 'M', '22', 2, 'asdf3@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf4', 'asdf4', 'asdf4', 'F', '23', 3, 'asdf4@a.com',3);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf5', 'asdf5', 'asdf5', 'M', '24', 0, 'asdf5@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf6', 'asdf6', 'asdf6', 'F', '25', 1, 'asdf6@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf7', 'asdf7', 'asdf7', 'M', '26', 2, 'asdf7@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf8', 'asdf8', 'asdf8', 'F', '27', 3, 'asdf8@a.com',3);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf9', 'asdf9', 'asdf9', 'M', '28', 0, 'asdf9@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf10', 'asdf10', 'asdf10', 'F', '29', 1, 'asdf10@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf11', 'asdf11', 'asdf11', 'M', '30', 2, 'asdf11@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf12', 'asdf12', 'asdf12', 'F', '31', 3, 'asdf12@a.com',3);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf13', 'asdf13', 'asdf13', 'M', '32', 0, 'asdf13@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf14', 'asdf14', 'asdf14', 'F', '33', 1, 'asdf14@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf15', 'asdf15', 'asdf15', 'M', '34', 2, 'asdf15@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf16', 'asdf16', 'asdf16', 'F', '35', 3, 'asdf16@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf17', 'asdf17', 'asdf17', 'M', '36', 0, 'asdf17@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf18', 'asdf18', 'asdf18', 'F', '37', 0, 'asdf18@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf19', 'asdf19', 'asdf19', 'M', '38', 0, 'asdf19@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf20', 'asdf20', 'asdf20', 'F', '39', 0, 'asdf20@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf21', 'asdf21', 'asdf21', 'M', '40', 0, 'asdf21@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf22', 'asdf22', 'asdf22', 'F', '41', 0, 'asdf22@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf23', 'asdf23', 'asdf23', 'M', '42', 0, 'asdf23@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf24', 'asdf24', 'asdf24', 'F', '43', 0, 'asdf24@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf25', 'asdf25', 'asdf25', 'M', '44', 0, 'asdf25@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf26', 'asdf26', 'asdf26', 'F', '45', 0, 'asdf26@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf27', 'asdf27', 'asdf27', 'M', '46', 0, 'asdf27@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf28', 'asdf28', 'asdf28', 'F', '47', 0, 'asdf28@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf29', 'asdf29', 'asdf29', 'M', '48', 0, 'asdf29@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf30', 'asdf30', 'asdf30', 'F', '49', 0, 'asdf30@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf31', 'asdf31', 'asdf31', 'M', '50', 0, 'asdf31@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf32', 'asdf32', 'asdf32', 'F', '51', 0, 'asdf32@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf33', 'asdf33', 'asdf33', 'M', '52', 0, 'asdf33@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf34', 'asdf34', 'asdf34', 'F', '53', 0, 'asdf34@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf35', 'asdf35', 'asdf35', 'M', '54', 0, 'asdf35@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf36', 'asdf36', 'asdf36', 'F', '55', 0, 'asdf36@a.com',3);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf37', 'asdf37', 'asdf37', 'M', '56', 0, 'asdf37@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf38', 'asdf38', 'asdf38', 'F', '57', 0, 'asdf38@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf39', 'asdf39', 'asdf39', 'M', '58', 0, 'asdf39@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf40', 'asdf40', 'asdf40', 'F', '59', 0, 'asdf40@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf41', 'asdf41', 'asdf41', 'M', '60', 0, 'asdf41@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf42', 'asdf42', 'asdf42', 'F', '61', 0, 'asdf42@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf43', 'asdf43', 'asdf43', 'M', '62', 0, 'asdf43@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf44', 'asdf44', 'asdf44', 'F', '63', 0, 'asdf44@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf45', 'asdf45', 'asdf45', 'M', '64', 0, 'asdf45@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf46', 'asdf46', 'asdf46', 'F', '65', 0, 'asdf46@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf47', 'asdf47', 'asdf47', 'M', '66', 0, 'asdf47@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf48', 'asdf48', 'asdf48', 'F', '67', 0, 'asdf48@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf49', 'asdf49', 'asdf49', 'M', '68', 0, 'asdf49@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf50', 'asdf50', 'asdf50', 'F', '69', 0, 'asdf50@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf51', 'asdf51', 'asdf51', 'M', '70', 0, 'asdf51@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf52', 'asdf52', 'asdf52', 'F', '71', 0, 'asdf52@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf53', 'asdf53', 'asdf53', 'M', '72', 0, 'asdf53@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf54', 'asdf54', 'asdf54', 'F', '73', 0, 'asdf54@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf55', 'asdf55', 'asdf55', 'M', '74', 0, 'asdf55@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf56', 'asdf56', 'asdf56', 'F', '75', 0, 'asdf56@a.com',1);



insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf57', 'asdf57', 'asdf57', 'M', '75', 1, 'asdf57@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf58', 'asdf58', 'asdf58', 'F', '20', 1, 'asdf58@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf59', 'asdf59', 'asdf59', 'M', '21', 1, 'asdf59@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf60', 'asdf60', 'asdf60', 'F', '22', 1, 'asdf60@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf61', 'asdf61', 'asdf61', 'M', '23', 1, 'asdf61@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf62', 'asdf62', 'asdf62', 'F', '24', 1, 'asdf62@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf63', 'asdf63', 'asdf63', 'M', '25', 1, 'asdf63@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf64', 'asdf64', 'asdf64', 'F', '26', 1, 'asdf64@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf65', 'asdf65', 'asdf65', 'M', '27', 1, 'asdf65@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf66', 'asdf66', 'asdf66', 'F', '28', 1, 'asdf66@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf67', 'asdf67', 'asdf67', 'M', '29', 1, 'asdf67@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf68', 'asdf68', 'asdf68', 'F', '30', 1, 'asdf68@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf69', 'asdf69', 'asdf69', 'M', '31', 1, 'asdf69@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf70', 'asdf70', 'asdf70', 'F', '32', 1, 'asdf70@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf71', 'asdf71', 'asdf71', 'M', '33', 1, 'asdf71@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf72', 'asdf72', 'asdf72', 'F', '34', 1, 'asdf72@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf73', 'asdf73', 'asdf73', 'M', '35', 1, 'asdf73@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf74', 'asdf74', 'asdf74', 'F', '36', 1, 'asdf74@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf75', 'asdf75', 'asdf75', 'M', '37', 1, 'asdf75@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf76', 'asdf76', 'asdf76', 'F', '38', 1, 'asdf76@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf77', 'asdf77', 'asdf77', 'M', '39', 1, 'asdf77@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf78', 'asdf78', 'asdf78', 'F', '40', 1, 'asdf78@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf79', 'asdf79', 'asdf79', 'M', '41', 1, 'asdf79@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf80', 'asdf80', 'asdf80', 'F', '42', 1, 'asdf80@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf81', 'asdf81', 'asdf81', 'M', '43', 1, 'asdf81@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf82', 'asdf82', 'asdf82', 'F', '44', 1, 'asdf82@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf83', 'asdf83', 'asdf83', 'M', '45', 1, 'asdf83@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf84', 'asdf84', 'asdf84', 'F', '46', 1, 'asdf84@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf85', 'asdf85', 'asdf85', 'M', '47', 1, 'asdf85@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf86', 'asdf86', 'asdf86', 'F', '48', 1, 'asdf86@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf87', 'asdf87', 'asdf87', 'M', '49', 1, 'asdf87@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf88', 'asdf88', 'asdf88', 'F', '50', 1, 'asdf88@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf89', 'asdf89', 'asdf89', 'M', '51', 1, 'asdf89@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf90', 'asdf90', 'asdf90', 'F', '52', 1, 'asdf90@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf91', 'asdf91', 'asdf91', 'M', '53', 1, 'asdf91@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf92', 'asdf92', 'asdf92', 'F', '54', 1, 'asdf92@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf93', 'asdf93', 'asdf93', 'M', '55', 1, 'asdf93@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf94', 'asdf94', 'asdf94', 'F', '56', 1, 'asdf94@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf95', 'asdf95', 'asdf95', 'M', '57', 1, 'asdf95@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf96', 'asdf96', 'asdf96', 'F', '58', 1, 'asdf96@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf97', 'asdf97', 'asdf97', 'M', '59', 1, 'asdf97@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf98', 'asdf98', 'asdf98', 'F', '60', 1, 'asdf98@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf99', 'asdf99', 'asdf99', 'M', '61', 1, 'asdf99@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf100', 'asdf100', 'asdf100', 'F', '62', 1, 'asdf100@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf101', 'asdf101', 'asdf101', 'M', '63', 1, 'asdf101@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf102', 'asdf102', 'asdf102', 'F', '64', 1, 'asdf102@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf103', 'asdf103', 'asdf103', 'M', '65', 1, 'asdf103@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf104', 'asdf104', 'asdf104', 'F', '66', 1, 'asdf104@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf105', 'asdf105', 'asdf105', 'M', '67', 1, 'asdf105@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf106', 'asdf106', 'asdf106', 'F', '68', 1, 'asdf106@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf107', 'asdf107', 'asdf107', 'M', '69', 1, 'asdf107@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf108', 'asdf108', 'asdf108', 'F', '70', 1, 'asdf108@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf109', 'asdf109', 'asdf109', 'M', '71', 1, 'asdf109@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf110', 'asdf110', 'asdf110', 'F', '72', 1, 'asdf110@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf111', 'asdf111', 'asdf111', 'M', '73', 1, 'asdf111@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf112', 'asdf112', 'asdf112', 'F', '20', 1, 'asdf112@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf113', 'asdf113', 'asdf113', 'M', '21', 1, 'asdf113@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf114', 'asdf114', 'asdf114', 'F', '22', 1, 'asdf114@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf115', 'asdf115', 'asdf115', 'M', '23', 1, 'asdf115@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf116', 'asdf116', 'asdf116', 'F', '24', 1, 'asdf116@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf117', 'asdf117', 'asdf117', 'M', '25', 1, 'asdf117@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf118', 'asdf118', 'asdf118', 'F', '26', 1, 'asdf118@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf119', 'asdf119', 'asdf119', 'M', '27', 1, 'asdf119@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf120', 'asdf120', 'asdf120', 'F', '28', 1, 'asdf120@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf121', 'asdf121', 'asdf121', 'M', '29', 1, 'asdf121@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf122', 'asdf122', 'asdf122', 'F', '30', 1, 'asdf122@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf123', 'asdf123', 'asdf123', 'M', '31', 1, 'asdf123@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf124', 'asdf124', 'asdf124', 'F', '32', 1, 'asdf124@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf125', 'asdf125', 'asdf125', 'M', '33', 1, 'asdf125@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf126', 'asdf126', 'asdf126', 'F', '34', 1, 'asdf126@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf127', 'asdf127', 'asdf127', 'M', '35', 1, 'asdf127@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf128', 'asdf128', 'asdf128', 'F', '36', 1, 'asdf128@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf129', 'asdf129', 'asdf129', 'M', '37', 1, 'asdf129@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf130', 'asdf130', 'asdf130', 'F', '38', 1, 'asdf130@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf131', 'asdf131', 'asdf131', 'M', '39', 1, 'asdf131@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf132', 'asdf132', 'asdf132', 'F', '40', 1, 'asdf132@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf133', 'asdf133', 'asdf133', 'M', '41', 1, 'asdf133@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf134', 'asdf134', 'asdf134', 'F', '42', 1, 'asdf134@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf135', 'asdf135', 'asdf135', 'M', '43', 1, 'asdf135@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf136', 'asdf136', 'asdf136', 'F', '44', 1, 'asdf136@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf137', 'asdf137', 'asdf137', 'M', '45', 1, 'asdf137@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf138', 'asdf138', 'asdf138', 'F', '46', 1, 'asdf138@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf139', 'asdf139', 'asdf139', 'M', '47', 1, 'asdf139@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf140', 'asdf140', 'asdf140', 'F', '48', 1, 'asdf140@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf141', 'asdf141', 'asdf141', 'M', '49', 1, 'asdf141@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf142', 'asdf142', 'asdf142', 'F', '50', 1, 'asdf142@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf143', 'asdf143', 'asdf143', 'M', '51', 1, 'asdf143@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf144', 'asdf144', 'asdf144', 'F', '52', 1, 'asdf144@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf145', 'asdf145', 'asdf145', 'M', '53', 1, 'asdf145@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf146', 'asdf146', 'asdf146', 'F', '54', 1, 'asdf146@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf147', 'asdf147', 'asdf147', 'M', '55', 1, 'asdf147@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf148', 'asdf148', 'asdf148', 'F', '56', 1, 'asdf148@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf149', 'asdf149', 'asdf149', 'M', '57', 1, 'asdf149@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf150', 'asdf150', 'asdf150', 'F', '58', 1, 'asdf150@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf151', 'asdf151', 'asdf151', 'M', '59', 1, 'asdf151@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf152', 'asdf152', 'asdf152', 'F', '60', 1, 'asdf152@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf153', 'asdf153', 'asdf153', 'M', '61', 1, 'asdf153@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf154', 'asdf154', 'asdf154', 'F', '62', 1, 'asdf154@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf155', 'asdf155', 'asdf155', 'M', '63', 1, 'asdf155@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf156', 'asdf156', 'asdf156', 'F', '64', 1, 'asdf156@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf157', 'asdf157', 'asdf157', 'M', '65', 1, 'asdf157@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf158', 'asdf158', 'asdf158', 'F', '66', 1, 'asdf158@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf159', 'asdf159', 'asdf159', 'M', '67', 1, 'asdf159@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf160', 'asdf160', 'asdf160', 'F', '68', 1, 'asdf160@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf161', 'asdf161', 'asdf161', 'M', '69', 1, 'asdf161@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf162', 'asdf162', 'asdf162', 'F', '70', 1, 'asdf162@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf163', 'asdf163', 'asdf163', 'M', '71', 1, 'asdf163@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf164', 'asdf164', 'asdf164', 'F', '72', 1, 'asdf164@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf165', 'asdf165', 'asdf165', 'M', '73', 1, 'asdf165@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf166', 'asdf166', 'asdf166', 'F', '74', 1, 'asdf166@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf167', 'asdf167', 'asdf167', 'M', '75', 1, 'asdf167@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf168', 'asdf168', 'asdf168', 'F', '76', 1, 'asdf168@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf169', 'asdf169', 'asdf169', 'M', '77', 1, 'asdf169@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf170', 'asdf170', 'asdf170', 'F', '78', 1, 'asdf170@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf171', 'asdf171', 'asdf171', 'M', '79', 1, 'asdf171@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf172', 'asdf172', 'asdf172', 'F', '80', 1, 'asdf172@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf173', 'asdf173', 'asdf173', 'M', '81', 1, 'asdf173@a.com',1);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf174', 'asdf174', 'asdf174', 'F', '82', 1, 'asdf174@a.com',2);
insert into tb_user2(user_id, user_pw, user_nick, user_gender, user_age, user_blockcnt, user_email, user_grade) values('asdf175', 'asdf175', 'asdf175', 'M', '83', 1, 'asdf175@a.com',1);

SELECT * FROM TB_USER2;


--신고 테이블
select * from tb_userreport2
order by user_no asc;

insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(2, sysdate, 1, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(3, sysdate, 2, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(3, sysdate, 3, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(4, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(4, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(4, sysdate, 1, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(6, sysdate, 2, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(7, sysdate, 3, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(7, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(8, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(8, sysdate, 1, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(8, sysdate, 2, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(10, sysdate, 3, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(11, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(11, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(12, sysdate, 1, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(12, sysdate, 2, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(12, sysdate, 3, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(14, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(15, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(15, sysdate, 1, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(16, sysdate, 2, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(16, sysdate, 3, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(16, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(17, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(18, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(19, sysdate, 4, null);



insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(60, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(61, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(62, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(63, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(64, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(65, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(66, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(67, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(68, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(69, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(70, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(71, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(72, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(73, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(74, sysdate, 3,null);

insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(75, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(76, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(77, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(78, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(79, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(80, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(81, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(82, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(83, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(84, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(85, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(86, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(87, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(88, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(89, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(90, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(91, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(92, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(93, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(94, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(95, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(96, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(97, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(98, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(99, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(100, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(101, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(102, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(103, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(104, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(105, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(106, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(107, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(108, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(109, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(110, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(111, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(112, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(113, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(114, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(115, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(116, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(117, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(118, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(119, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(120, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(121, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(122, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(123, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(124, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(125, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(126, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(127, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(128, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(129, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(130, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(131, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(132, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(133, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(134, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(135, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(136, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(137, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(138, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(139, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(140, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(141, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(142, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(143, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(144, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(145, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(146, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(147, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(148, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(149, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(150, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(151, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(152, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(153, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(154, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(155, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(156, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(157, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(158, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(159, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(160, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(161, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(162, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(163, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(164, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(165, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(166, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(167, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(168, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(169, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(170, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(171, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(172, sysdate, 1,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(173, sysdate, 2,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(174, sysdate, 3,null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(175, sysdate, 4, null);
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(176, sysdate, 5, 'test');
insert into tb_userreport2 (user_no, report_time, reason_no, report_content) values(177, sysdate, 1,null);




select * from tb_user2;

--신고처리 더미데이터
insert into tb_resultreport2 (user_no, report_result_date, report_result_detail_no) values(4, sysdate, 1);
insert into tb_resultreport2 (user_no, report_result_date, report_result_detail_no) values(8, sysdate, 1);
insert into tb_resultreport2 (user_no, report_result_date, report_result_detail_no) values(12, sysdate, 1);

select * from tb_resultreport2;
commit;
