--공지사항 더미데이터
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 이용약관 및 개인정보처리방침 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 1023);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 개인정보처리방침 변경 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 359);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 평점 업데이트.', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 994);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 1월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 492);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 2월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 975);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 3월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 432);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 개인정보처리방침 일부 변경 안내.', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 336);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 이용약관 변경 안내.', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 856);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 6월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 922);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 8월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 1342);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 명절 및 연휴 고객센터 이용 불가', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 785);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 신고 관련 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 223);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 안전한 서비스 이용을 위한 도움말', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 346);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 결제 관련', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 234);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 10월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 332);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 11월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 231);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 12월 서비스 점검 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 543);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 메이트 찾기 서비스 기능 추가', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 223);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 채팅 관련', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 321);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 오픈기념 결제 할인 이벤트', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 532);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 사업 확장 및 내부 공사 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 112);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 커뮤니티 관련 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 59);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit)
    VALUES (tb_noticeboard_seq.nextval,  NVL('MEETEAT 고객 지원 서비스 변경 안내', '(제목없음)'), '불러 별 하나에 추억과 당신은 언덕 거외다. 흙으로 계절이 멀리 헤는 사람들의 아이들의 가슴속에 까닭입니다. 차 하나의 멀리 계절이 듯합니다. 까닭이요, 이름을 새워 북간도에 별 피어나듯이 거외다. 오는 밤이 흙으로 때 있습니다. 무덤 무엇인지 시인의 아침이 봅니다. 멀듯이, 불러 아이들의 이름과, 패, 하나에 아스라히 당신은 마리아 있습니다. 이름과, 마디씩 나는 풀이 별에도 가난한 봄이 버리었습니다. 별을 별 한 봄이 애기 하나 있습니다. 보고, 가을 것은 언덕 다 별 때 없이 딴은 봅니다.', 1, 1, sysdate, sysdate, 0, 0);

--문의사항 더미데이터
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제가 안 됩니다.', '(제목없음)'), '결제가 안 됩니다. 확인 후 답변 부탁드립니다.', 5, 5,sysdate, sysdate, 0, 25, 1, 0, 0, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제는 어떻게 진행되는건가요?', '(제목없음)'), '결제는 어떻게 진행되는건가요?  월마다 결제를 해야 하는 건가요?', 5, 6,sysdate, sysdate, 0, 13, 2, 0, 0, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('메이트 찾기가 안 되는데 어떻게 해야 하나요?', '(제목없음)'), '메이트 찾기 게시판에 들어가면 찾기가 안됩니다.', 5, 7,sysdate, sysdate, 0, 17, 3, 0, 0, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('이벤트 신청 했는데 확인 부탁드립니다.', '(제목없음)'), '이벤트 신청 했는데 확인 부탁드립니다.', 5, 8,sysdate, sysdate, 0, 6, 4, 0, 0, 0); 
    
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제 확인 되었습니다.', '(제목없음)'), '결제가 확인이 되었습니다. 서비스 이용이 가능합니다.', 5, 1,sysdate, sysdate, 0, 42, 1, 2, 1, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제 관련 안내 해드리겠습니다.', '(제목없음)'), '월 4900원으로 이용가능하며, 월 11900원 정기 결제로 모든 서비스를 이용하실 수 있습니다.', 5, 1,sysdate, sysdate, 0, 31, 2, 2, 1, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('이용에 불편을 드려 죄송합니다.', '(제목없음)'), '오류 사항을 확인 후 수정되었습니다. 좋은 하루 되세요. 감사합니다^^', 5, 1,sysdate, sysdate, 0, 11, 3, 2, 1, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('어떤 이벤트를 신청 하셨나요?', '(제목없음)'), '자세한 문의 내용을 부탁드립니다.', 5, 1,sysdate, sysdate, 0, 8, 4, 2, 1, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('확인 부탁드립니다.', '(제목없음)'), '맛집 이벤트 신청을 하였습니다.', 5, 8,sysdate, sysdate, 0, 19, 4, 4, 2, 0);
    
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('급합니다!! 빠른 확인 부탁드립니다!!', '(제목없음)'), '서비스를 이용 할 수가 없습니다.빠른 처리 부탁드립니다.', 5, 10,sysdate, sysdate, 0, 2, 10, 0, 0, 1);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('커뮤니티 관련하여 궁금합니다.', '(제목없음)'), '어떻게 글을 작성하는 건가요?', 5, 11,sysdate, sysdate, 0, 19, 11, 0, 0, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제가 되었는데', '(제목없음)'), '결제가 되었는데 왜 서비스를 이용할 수가 없는 거죠?  확인 부탁드립니다.', 5, 12,sysdate, sysdate, 0, 2, 12, 0, 0, 1);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('고객센터에 전화 연결이 안됩니다.', '(제목없음)'), '고객센터 전화연결이 안됩니다!!.', 5, 13,sysdate, sysdate, 0, 3, 13, 0, 0, 1);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('서비스를 이용 할 수가 없습니다.', '(제목없음)'), '서비스를 이용 할 수가 없습니다.빠른 처리 부탁드립니다.', 5, 14,sysdate, sysdate, 0, 10, 14, 0, 0, 0);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('채팅 문의 입니다,', '(제목없음)'), '채팅 문의입니다', 5, 15,sysdate, sysdate, 0, 2, 15, 0, 0, 1);
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('채팅 관련 답변입니다.', '(제목없음)'), '수정되었습니다.', 5, 1,sysdate, sysdate, 0, 6, 15, 2, 1, 1);
    
INSERT INTO tb_board2 (article_no, article_title, article_content, board_no, user_no, create_date, revision_date, is_delete, article_hit, post_group, post_step, post_indent, article_secret)
    VALUES (tb_inquiryboard_seq.nextval,  NVL('결제관련해서 답변드립니다.', '(제목없음)'), '결제확인이되었습니다. 서비스이용해주셔서 감사합니다.', 5, 1,sysdate, sysdate, 0, 4, 12, 2, 1, 1);
     
commit;